### ISSUE TITLE
about the polarity marking of 1uF capacitor,

### ISSUE THREAD

**Issue by ws786873** [xavpaice/MFOS-wallwart#1]
I used 1uF tantalum capacitors. They seem to have polarity and are also marked in the original version. So can you add them? Although I succeeded in making a power supply after trying to read the schematic diagram, before I succeeded, I saw the magic smoke XD

**Comment by xavpaice** [comment]
Thanks for the report.  Sorry it took me ages, but I got to make another one and am using polarized caps like you.  I've put the markings on the board and updated to the kicad in Ubuntu Jammy.  Note this is untested, if I make smoke I'll fix the board.
